### ISSUE TITLE
support new for loops

### ISSUE THREAD

**Issue by nektro** [marlersoft/zigwin32gen#21]
`for (slice) |item, i|` -> `for (slice, 0..) |item, i|`

change as of 0.11.0-dev.1681+0bb178bbb

**Comment by desttinghim** [comment]
Looks like #20 implements this

**Comment by marler8997** [comment]
Done in https://github.com/marlersoft/zigwin32gen/commit/024361b0801962eceba4652593118a7ebc39a487
